/* ==========================================
   CSS Reference (A-Z) — data-driven renderer
   出典目次：とほほのCSS入門
   ========================================== */

/*  各項目の形式:
    { n: 名称, k: 種別, d: 一言説明, c: コード例, p: プレビューHTML(任意) }
    k: selector | property | function | at-rule | pseudo | type | global
    p を省略すると「プレビューなし」カードになる
*/

const REF = {};

/* ----- 記号・その他（セレクタ群） ----- */
REF.sym = [
  { n: "tagName { }", k: "selector", d: "要素型セレクタ", c: "p { color: crimson; }",
    p: `<p style="color:crimson;margin:0">&lt;p&gt;に適用</p>` },
  { n: ".class { }", k: "selector", d: "クラスセレクタ", c: ".note { color: teal; }",
    p: `<span style="color:teal;font-weight:700">.note</span>` },
  { n: "#id { }", k: "selector", d: "IDセレクタ", c: "#top { border: 1px solid #333; }",
    p: `<span style="border:1px solid #333;padding:0 4px">#top</span>` },
  { n: "* { }", k: "selector", d: "全称セレクタ", c: "* { box-sizing: border-box; }" },
  { n: "ns|E { }", k: "selector", d: "名前空間つき要素", c: "svg|rect { fill: crimson; }" },
  { n: "[attr]", k: "selector", d: "属性が存在", c: "a[target] { color: navy; }",
    p: `<a style="color:navy" target="_blank">target付きリンク</a>` },
  { n: '[attr="val"]', k: "selector", d: "属性が完全一致", c: 'input[type="text"] { background:#ffd; }' },
  { n: '[attr~="val"]', k: "selector", d: "空白区切りで一致", c: '[class~="btn"] { }' },
  { n: '[attr|="val"]', k: "selector", d: "valまたはval-から始まる", c: '[lang|="ja"] { }' },
  { n: '[attr^="val"]', k: "selector", d: "前方一致", c: 'a[href^="https"] { }' },
  { n: '[attr$="val"]', k: "selector", d: "後方一致", c: 'a[href$=".pdf"] { }' },
  { n: '[attr*="val"]', k: "selector", d: "部分一致", c: 'a[href*="example"] { }' },
  { n: "[ns|attr]", k: "selector", d: "名前空間つき属性", c: "[xlink|href] { }" },
  { n: "E, F", k: "selector", d: "グルーピング（列挙）", c: "h1, h2, h3 { color: #333; }" },
  { n: "E F", k: "selector", d: "子孫セレクタ", c: "nav a { color: #fff; }" },
  { n: "E > F", k: "selector", d: "子セレクタ", c: "ul > li { list-style: square; }" },
  { n: "E + F", k: "selector", d: "隣接兄弟", c: "h2 + p { margin-top: 0; }" },
  { n: "E ~ F", k: "selector", d: "一般兄弟", c: "h2 ~ p { color: #666; }" },
  { n: "E || F", k: "selector", d: "同じ表の列", c: "col.sel || td { background: #ffd; }" },
];

/* ----- A ----- */
REF.A = [
  { n: "abs()", k: "function", d: "絶対値", c: "width: abs(-10px); /* 10px */" },
  { n: "accent-color", k: "property", d: "フォーム要素のアクセント色", c: "accent-color: crimson;",
    p: `<input type="checkbox" checked style="accent-color:crimson"><input type="radio" checked style="accent-color:crimson">` },
  { n: "acos()", k: "function", d: "逆余弦", c: "rotate: acos(-1); /* 180deg */" },
  { n: ":active", k: "pseudo", d: "押下中", c: "a:active { color: red; }",
    p: `<a style="color:#333" onmousedown="this.style.color='red'" onmouseup="this.style.color='#333'">押してみる</a>` },
  { n: "::after", k: "pseudo", d: "要素の直後に生成", c: 'a::after { content: " →"; }',
    p: `<span>リンク<span style="color:#888">&nbsp;→</span></span>` },
  { n: "align-content", k: "property", d: "交差軸の整列（複数行）", c: "align-content: center;",
    p: `<div style="display:flex;flex-wrap:wrap;align-content:center;height:50px;gap:3px;background:#eee"><span style="background:#6b4423;color:#fff;padding:2px 6px">A</span><span style="background:#6b4423;color:#fff;padding:2px 6px">B</span></div>` },
  { n: "align-items", k: "property", d: "交差軸の整列", c: "align-items: center;",
    p: `<div style="display:flex;align-items:center;height:50px;gap:4px;background:#eee"><span style="background:#6b4423;color:#fff;padding:2px 6px">A</span><span style="background:#6b4423;color:#fff;padding:2px 6px;font-size:1.4em">B</span></div>` },
  { n: "align-self", k: "property", d: "自分だけ交差軸整列を上書き", c: "align-self: flex-end;",
    p: `<div style="display:flex;height:50px;gap:4px;background:#eee"><span style="background:#6b4423;color:#fff;padding:2px 6px">A</span><span style="align-self:flex-end;background:crimson;color:#fff;padding:2px 6px">B</span></div>` },
  { n: "all", k: "property", d: "全プロパティを一括指定", c: "all: revert;" },
  { n: "anchor()", k: "function", d: "アンカー要素を参照した位置指定", c: "top: anchor(bottom);" },
  { n: "anchor-name", k: "property", d: "アンカー要素に名前を付与", c: "anchor-name: --btn;" },
  { n: "anchor-size()", k: "function", d: "アンカーのサイズを参照", c: "width: anchor-size(width);" },
  { n: "anchor-scope", k: "property", d: "アンカー参照の範囲", c: "anchor-scope: --btn;" },
  { n: "<angle>", k: "type", d: "角度(deg/rad/grad/turn)", c: "transform: rotate(45deg);",
    p: `<span style="display:inline-block;background:#6b4423;color:#fff;padding:2px 8px;transform:rotate(45deg)">45deg</span>` },
  { n: "animation", k: "property", d: "アニメーション一括指定", c: "animation: pulse 1s infinite;",
    p: `<span style="display:inline-block;width:20px;height:20px;border-radius:50%;background:#6b4423;animation:refPulse 1s infinite"></span><style>@keyframes refPulse{50%{transform:scale(1.4);opacity:.5}}</style>` },
  { n: "animation-composition", k: "property", d: "重ねがけ時の合成方法", c: "animation-composition: add;" },
  { n: "animation-delay", k: "property", d: "開始遅延", c: "animation-delay: 0.5s;" },
  { n: "animation-direction", k: "property", d: "再生方向", c: "animation-direction: alternate;" },
  { n: "animation-duration", k: "property", d: "一回あたりの時間", c: "animation-duration: 1.5s;" },
  { n: "animation-fill-mode", k: "property", d: "前後の状態を保持", c: "animation-fill-mode: forwards;" },
  { n: "animation-iteration-count", k: "property", d: "繰り返し回数", c: "animation-iteration-count: infinite;" },
  { n: "animation-name", k: "property", d: "@keyframes名", c: "animation-name: pulse;" },
  { n: "animation-play-state", k: "property", d: "再生/一時停止", c: "animation-play-state: paused;" },
  { n: "animation-range", k: "property", d: "スクロール駆動の範囲", c: "animation-range: cover;" },
  { n: "animation-range-end", k: "property", d: "範囲の終点", c: "animation-range-end: 80%;" },
  { n: "animation-range-start", k: "property", d: "範囲の始点", c: "animation-range-start: 20%;" },
  { n: "animation-timeline", k: "property", d: "スクロールなどの駆動源", c: "animation-timeline: scroll();" },
  { n: "animation-timing-function", k: "property", d: "加減速曲線", c: "animation-timing-function: ease-in-out;" },
  { n: "animation-trigger", k: "property", d: "再生トリガ", c: "animation-trigger: view();" },
  { n: ":any-link", k: "pseudo", d: "href付きの a/area/link", c: ":any-link { color: #06c; }",
    p: `<a href="#" style="color:#06c;text-decoration:underline">href付き</a> / <a style="color:#06c;text-decoration:underline">href無し</a>` },
  { n: "appearance", k: "property", d: "既定UIを解除", c: "appearance: none;",
    p: `<button style="padding:2px 8px">既定</button> <button style="appearance:none;-webkit-appearance:none;padding:2px 8px;background:#6b4423;color:#fff;border:none">none</button>` },
  { n: "asin()", k: "function", d: "逆正弦", c: "rotate: asin(1); /* 90deg */" },
  { n: "aspect-ratio", k: "property", d: "縦横比を固定", c: "aspect-ratio: 16/9;",
    p: `<div style="width:80px;aspect-ratio:16/9;background:#6b4423"></div>` },
  { n: "atan()", k: "function", d: "逆正接", c: "rotate: atan(1); /* 45deg */" },
  { n: "atan2()", k: "function", d: "2引数逆正接", c: "rotate: atan2(1,1); /* 45deg */" },
  { n: "attr()", k: "function", d: "属性値を取得", c: 'content: attr(data-label);',
    p: `<style>.ref-attr-demo::before{content:"[" attr(data-label) "] ";color:#6b4423;font-weight:700}</style><span class="ref-attr-demo" data-label="NEW">新機能</span>` },
  { n: ":autofill", k: "pseudo", d: "ブラウザ自動入力中", c: "input:autofill { background: #ffd; }" },
  { n: "azimuth", k: "property", d: "音源の方位（deprecated）", c: "azimuth: center;" },
];

/* ----- B ----- */
REF.B = [
  { n: "::backdrop", k: "pseudo", d: "dialog/fullscreenの背景", c: "::backdrop { background: #0008; }",
    p: `<div style="position:relative;width:100%;height:50px;background:#333;border-radius:4px;overflow:hidden"><div style="position:absolute;inset:0;background:#0008"></div><div style="position:absolute;inset:12px 20px;background:#fff;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:.9em">dialog</div></div>` },
  { n: "backdrop-filter", k: "property", d: "背後にフィルター", c: "backdrop-filter: blur(6px);",
    p: `<div style="position:relative;width:100%;height:50px;background:linear-gradient(90deg,#6b4423,#c38),contain:content;overflow:hidden"><div style="position:absolute;inset:10px 20px;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);background:#fff4;border-radius:6px"></div></div>` },
  { n: "backface-visibility", k: "property", d: "背面の可視制御", c: "backface-visibility: hidden;" },
  { n: "background", k: "property", d: "背景の一括指定", c: "background: #6b4423 url(a.jpg) center/cover;",
    p: `<div style="background:#6b4423;padding:4px 8px;color:#fff;display:inline-block">背景</div>` },
  { n: "background-attachment", k: "property", d: "背景のスクロール固定", c: "background-attachment: fixed;" },
  { n: "background-blend-mode", k: "property", d: "複数背景の合成", c: "background-blend-mode: multiply;",
    p: `<div style="width:60px;height:40px;background:linear-gradient(90deg,#c38,#6b4423),radial-gradient(#fff,#000);background-blend-mode:multiply"></div>` },
  { n: "background-clip", k: "property", d: "背景の描画範囲", c: "background-clip: text;",
    p: `<span style="background:linear-gradient(90deg,#c38,#6b4423);-webkit-background-clip:text;background-clip:text;color:transparent;font-weight:900;font-size:1.2em">ABC</span>` },
  { n: "background-color", k: "property", d: "背景色", c: "background-color: #fff8e7;",
    p: `<div style="background:#fff8e7;padding:6px">bg</div>` },
  { n: "background-image", k: "property", d: "背景画像", c: "background-image: url(a.jpg);",
    p: `<div style="width:60px;height:40px;background-image:linear-gradient(45deg,#c38,#6b4423)"></div>` },
  { n: "background-origin", k: "property", d: "背景の基準", c: "background-origin: content-box;" },
  { n: "background-position", k: "property", d: "背景の位置", c: "background-position: center;",
    p: `<div style="width:60px;height:40px;background:radial-gradient(circle 10px at center,#6b4423 99%,#eee 100%);background-repeat:no-repeat"></div>` },
  { n: "background-position-x", k: "property", d: "背景の横位置", c: "background-position-x: right;" },
  { n: "background-position-y", k: "property", d: "背景の縦位置", c: "background-position-y: top;" },
  { n: "background-repeat", k: "property", d: "タイル繰り返し", c: "background-repeat: no-repeat;",
    p: `<div style="width:60px;height:40px;background:repeating-linear-gradient(45deg,#6b4423 0 6px,#eee 6px 12px)"></div>` },
  { n: "background-size", k: "property", d: "背景サイズ", c: "background-size: cover;",
    p: `<div style="display:flex;gap:4px"><div style="width:30px;height:30px;background:radial-gradient(#6b4423,#eee);background-size:100% 100%"></div><div style="width:30px;height:30px;background:radial-gradient(#6b4423,#eee);background-size:60% 60%;background-repeat:no-repeat;background-position:center;background-color:#eee"></div></div>` },
  { n: "::before", k: "pseudo", d: "要素の直前に生成", c: '::before { content: "▶"; }',
    p: `<span><span style="color:#6b4423">▶</span>項目</span>` },
  { n: "behavior", k: "property", d: "旧IE独自", c: "behavior: url(x.htc);" },
  { n: ":blank", k: "pseudo", d: "空白入力欄", c: "input:blank { border-color: #ccc; }" },
  { n: "block-size", k: "property", d: "論理軸の縦サイズ", c: "block-size: 100px;" },
  { n: "blur()", k: "function", d: "ぼかしフィルター", c: "filter: blur(3px);",
    p: `<span style="filter:blur(1.5px);font-weight:700">Blurred</span>` },
  { n: "border", k: "property", d: "枠線の一括", c: "border: 1px solid #6b4423;",
    p: `<span style="border:1px solid #6b4423;padding:2px 6px">枠</span>` },
  { n: "border-block", k: "property", d: "論理ブロック軸の枠", c: "border-block: 1px solid #000;" },
  { n: "border-block-color", k: "property", d: "ブロック軸 枠色", c: "border-block-color: red;" },
  { n: "border-block-end", k: "property", d: "ブロック終端の枠", c: "border-block-end: 2px solid;" },
  { n: "border-block-end-color", k: "property", d: "", c: "border-block-end-color: red;" },
  { n: "border-block-end-style", k: "property", d: "", c: "border-block-end-style: dashed;" },
  { n: "border-block-end-width", k: "property", d: "", c: "border-block-end-width: 3px;" },
  { n: "border-block-start", k: "property", d: "ブロック始点の枠", c: "border-block-start: 2px solid;" },
  { n: "border-block-start-color", k: "property", d: "", c: "border-block-start-color: red;" },
  { n: "border-block-start-style", k: "property", d: "", c: "border-block-start-style: dotted;" },
  { n: "border-block-start-width", k: "property", d: "", c: "border-block-start-width: 3px;" },
  { n: "border-block-style", k: "property", d: "", c: "border-block-style: solid;" },
  { n: "border-block-width", k: "property", d: "", c: "border-block-width: 2px;" },
  { n: "border-bottom", k: "property", d: "下枠線", c: "border-bottom: 2px solid #6b4423;",
    p: `<span style="border-bottom:2px solid #6b4423;padding-bottom:2px">下線</span>` },
  { n: "border-bottom-color", k: "property", d: "", c: "border-bottom-color: red;" },
  { n: "border-bottom-left-radius", k: "property", d: "", c: "border-bottom-left-radius: 12px;" },
  { n: "border-bottom-right-radius", k: "property", d: "", c: "border-bottom-right-radius: 12px;" },
  { n: "border-bottom-style", k: "property", d: "", c: "border-bottom-style: double;" },
  { n: "border-bottom-width", k: "property", d: "", c: "border-bottom-width: 3px;" },
  { n: "border-collapse", k: "property", d: "表の枠を結合", c: "border-collapse: collapse;",
    p: `<table style="border-collapse:collapse;font-size:.8em"><tr><td style="border:1px solid #6b4423;padding:2px 6px">A</td><td style="border:1px solid #6b4423;padding:2px 6px">B</td></tr></table>` },
  { n: "border-color", k: "property", d: "枠色", c: "border-color: #6b4423;",
    p: `<span style="border:2px solid crimson;padding:2px 6px">red枠</span>` },
  { n: "border-end-end-radius", k: "property", d: "論理 右下角", c: "border-end-end-radius: 12px;" },
  { n: "border-end-start-radius", k: "property", d: "論理 左下角", c: "border-end-start-radius: 12px;" },
  { n: "border-image", k: "property", d: "枠線に画像", c: "border-image: url(f.png) 30 round;",
    p: `<span style="display:inline-block;padding:4px 10px;border:6px solid transparent;border-image:linear-gradient(90deg,#c38,#6b4423,#c38) 1">グラデ枠</span>` },
  { n: "border-image-outset", k: "property", d: "", c: "border-image-outset: 4px;" },
  { n: "border-image-repeat", k: "property", d: "", c: "border-image-repeat: round;" },
  { n: "border-image-slice", k: "property", d: "", c: "border-image-slice: 30;" },
  { n: "border-image-source", k: "property", d: "", c: "border-image-source: url(f.png);" },
  { n: "border-image-width", k: "property", d: "", c: "border-image-width: 10px;" },
  { n: "border-inline", k: "property", d: "論理インライン軸の枠", c: "border-inline: 1px solid;" },
  { n: "border-inline-color", k: "property", d: "", c: "border-inline-color: red;" },
  { n: "border-inline-end", k: "property", d: "", c: "border-inline-end: 2px solid;" },
  { n: "border-inline-end-color", k: "property", d: "", c: "border-inline-end-color: red;" },
  { n: "border-inline-end-style", k: "property", d: "", c: "border-inline-end-style: dashed;" },
  { n: "border-inline-end-width", k: "property", d: "", c: "border-inline-end-width: 2px;" },
  { n: "border-inline-start", k: "property", d: "", c: "border-inline-start: 2px solid;" },
  { n: "border-inline-start-color", k: "property", d: "", c: "border-inline-start-color: red;" },
  { n: "border-inline-start-style", k: "property", d: "", c: "border-inline-start-style: solid;" },
  { n: "border-inline-start-width", k: "property", d: "", c: "border-inline-start-width: 2px;" },
  { n: "border-inline-style", k: "property", d: "", c: "border-inline-style: solid;" },
  { n: "border-inline-width", k: "property", d: "", c: "border-inline-width: 2px;" },
  { n: "border-left", k: "property", d: "左枠線", c: "border-left: 3px solid #6b4423;",
    p: `<span style="border-left:3px solid #6b4423;padding-left:6px">引用</span>` },
  { n: "border-left-color", k: "property", d: "", c: "border-left-color: red;" },
  { n: "border-left-style", k: "property", d: "", c: "border-left-style: dotted;" },
  { n: "border-left-width", k: "property", d: "", c: "border-left-width: 3px;" },
  { n: "border-radius", k: "property", d: "角を丸く", c: "border-radius: 8px;",
    p: `<div style="width:40px;height:40px;background:#6b4423;border-radius:8px"></div>` },
  { n: "border-right", k: "property", d: "右枠線", c: "border-right: 2px solid;",
    p: `<span style="border-right:3px solid #6b4423;padding-right:6px">右線</span>` },
  { n: "border-right-color", k: "property", d: "", c: "border-right-color: red;" },
  { n: "border-right-style", k: "property", d: "", c: "border-right-style: solid;" },
  { n: "border-right-width", k: "property", d: "", c: "border-right-width: 2px;" },
  { n: "border-spacing", k: "property", d: "表セル間隔", c: "border-spacing: 4px;" },
  { n: "border-start-end-radius", k: "property", d: "論理 右上角", c: "border-start-end-radius: 12px;" },
  { n: "border-start-start-radius", k: "property", d: "論理 左上角", c: "border-start-start-radius: 12px;" },
  { n: "border-style", k: "property", d: "枠線の線種", c: "border-style: dashed;",
    p: `<span style="border:2px dashed #6b4423;padding:2px 6px">dashed</span> <span style="border:2px dotted #6b4423;padding:2px 6px">dotted</span> <span style="border:2px double #6b4423;padding:2px 6px">double</span>` },
  { n: "border-top", k: "property", d: "上枠線", c: "border-top: 2px solid;",
    p: `<span style="border-top:3px solid #6b4423;padding-top:2px;display:inline-block">上線</span>` },
  { n: "border-top-color", k: "property", d: "", c: "border-top-color: red;" },
  { n: "border-top-left-radius", k: "property", d: "", c: "border-top-left-radius: 12px;" },
  { n: "border-top-right-radius", k: "property", d: "", c: "border-top-right-radius: 12px;" },
  { n: "border-top-style", k: "property", d: "", c: "border-top-style: groove;" },
  { n: "border-top-width", k: "property", d: "", c: "border-top-width: 3px;" },
  { n: "border-width", k: "property", d: "枠線の太さ", c: "border-width: 2px;",
    p: `<span style="border:1px solid #6b4423;padding:1px 4px">1px</span> <span style="border:4px solid #6b4423;padding:1px 4px">4px</span>` },
  { n: "bottom", k: "property", d: "配置位置(下)", c: "bottom: 10px;" },
  { n: "box-decoration-break", k: "property", d: "折り返し時の装飾の連続性", c: "box-decoration-break: clone;" },
  { n: "box-shadow", k: "property", d: "影", c: "box-shadow: 0 4px 10px #0002;",
    p: `<div style="width:40px;height:40px;background:#fff;box-shadow:0 4px 10px #0003"></div>` },
  { n: "box-sizing", k: "property", d: "サイズ計算の基準", c: "box-sizing: border-box;",
    p: `<div style="display:flex;gap:4px;font-size:.75em"><div style="box-sizing:content-box;width:40px;padding:4px;border:2px solid #6b4423;background:#fff8e7">content</div><div style="box-sizing:border-box;width:40px;padding:4px;border:2px solid #6b4423;background:#fff8e7">border</div></div>` },
  { n: "break-after", k: "property", d: "印刷時 要素後で改ページ", c: "break-after: page;" },
  { n: "break-before", k: "property", d: "要素前で改ページ", c: "break-before: page;" },
  { n: "break-inside", k: "property", d: "要素内で改ページ禁止等", c: "break-inside: avoid;" },
  { n: "brightness()", k: "function", d: "明度フィルター", c: "filter: brightness(1.3);" },
];

/* ----- C ----- */
REF.C = [
  { n: "calc()", k: "function", d: "値の計算", c: "width: calc(100% - 40px);",
    p: `<div style="width:calc(100% - 20px);background:#6b4423;color:#fff;padding:2px 6px;font-size:.8em">100%-20px</div>` },
  { n: "calc-size()", k: "function", d: "intrinsicサイズとの計算", c: "width: calc-size(auto, size + 20px);" },
  { n: "caption-side", k: "property", d: "表タイトルの位置", c: "caption-side: bottom;" },
  { n: "caret-animation", k: "property", d: "キャレット点滅制御", c: "caret-animation: manual;" },
  { n: "caret-color", k: "property", d: "キャレット色", c: "caret-color: crimson;",
    p: `<input type="text" value="編集" style="caret-color:crimson">` },
  { n: "caret-shape", k: "property", d: "キャレット形状", c: "caret-shape: block;" },
  { n: "@charset", k: "at-rule", d: "CSSの文字エンコーディング宣言", c: '@charset "UTF-8";' },
  { n: ":checked", k: "pseudo", d: "チェック状態", c: "input:checked { outline: 2px solid crimson; }",
    p: `<input type="checkbox" checked>` },
  { n: "clamp()", k: "function", d: "min-preferred-max を一つで", c: "font-size: clamp(14px, 2vw, 22px);" },
  { n: "clear", k: "property", d: "float回り込み解除", c: "clear: both;" },
  { n: "clip", k: "property", d: "矩形クリップ(deprecated)", c: "clip: rect(0,50px,50px,0);" },
  { n: "clip-path", k: "property", d: "表示領域を図形に", c: "clip-path: circle(50%);",
    p: `<div style="width:40px;height:40px;background:#6b4423;clip-path:circle(50%)"></div>` },
  { n: "color", k: "property", d: "文字色", c: "color: crimson;",
    p: `<span style="color:crimson">文字色</span>` },
  { n: "<color>", k: "type", d: "色データ型", c: "color: rgb(107 68 35);" },
  { n: "color-scheme", k: "property", d: "ライト/ダーク対応", c: "color-scheme: light dark;" },
  { n: "column-count", k: "property", d: "段組み数", c: "column-count: 3;",
    p: `<div style="column-count:3;column-gap:6px;font-size:.7em;line-height:1.2">ABC DEF GHI JKL MNO PQR STU VWX</div>` },
  { n: "column-fill", k: "property", d: "段の埋め方", c: "column-fill: balance;" },
  { n: "column-gap", k: "property", d: "段間", c: "column-gap: 2em;" },
  { n: "column-height", k: "property", d: "各段の高さ", c: "column-height: 200px;" },
  { n: "column-rule", k: "property", d: "段区切り線の一括", c: "column-rule: 1px dashed #999;",
    p: `<div style="column-count:2;column-rule:1px dashed #6b4423;column-gap:10px;font-size:.7em">ABCDEF GHIJKL</div>` },
  { n: "column-rule-color", k: "property", d: "", c: "column-rule-color: red;" },
  { n: "column-rule-style", k: "property", d: "", c: "column-rule-style: solid;" },
  { n: "column-rule-width", k: "property", d: "", c: "column-rule-width: 2px;" },
  { n: "column-span", k: "property", d: "段組みをまたぐ", c: "column-span: all;" },
  { n: "column-width", k: "property", d: "段の最小幅", c: "column-width: 200px;" },
  { n: "column-wrap", k: "property", d: "段ラップ", c: "column-wrap: wrap;" },
  { n: "columns", k: "property", d: "段組みの一括", c: "columns: 3 200px;" },
  { n: "conic-gradient()", k: "function", d: "円錐グラデ", c: "background: conic-gradient(red,yellow,lime,red);",
    p: `<div style="width:40px;height:40px;border-radius:50%;background:conic-gradient(red,yellow,lime,red)"></div>` },
  { n: "contain", k: "property", d: "影響範囲を制限", c: "contain: layout paint;" },
  { n: "contain-intrinsic-block-size", k: "property", d: "", c: "contain-intrinsic-block-size: 200px;" },
  { n: "contain-intrinsic-height", k: "property", d: "", c: "contain-intrinsic-height: 200px;" },
  { n: "contain-intrinsic-inline-size", k: "property", d: "", c: "contain-intrinsic-inline-size: 300px;" },
  { n: "contain-intrinsic-size", k: "property", d: "contain使用時の仮想サイズ", c: "contain-intrinsic-size: 300px 200px;" },
  { n: "contain-intrinsic-width", k: "property", d: "", c: "contain-intrinsic-width: 300px;" },
  { n: "@container", k: "at-rule", d: "コンテナクエリ", c: "@container (min-width: 400px) { .c { font-size: 1.2em; } }" },
  { n: "container", k: "property", d: "コンテナ種別の一括", c: "container: card / inline-size;" },
  { n: "container-name", k: "property", d: "", c: "container-name: card;" },
  { n: "container-type", k: "property", d: "", c: "container-type: inline-size;" },
  { n: "content", k: "property", d: "疑似要素に内容挿入", c: 'content: "▶";',
    p: `<style>.ref-content-demo::before{content:"▶ ";color:#6b4423}</style><span class="ref-content-demo">アイテム</span>` },
  { n: "content-visibility", k: "property", d: "レンダリング遅延", c: "content-visibility: auto;" },
  { n: "contrast()", k: "function", d: "コントラストフィルタ", c: "filter: contrast(1.5);",
    p: `<span style="filter:contrast(1.8);background:#eee;padding:2px 6px;font-weight:700">High</span>` },
  { n: "corner-block-end-shape", k: "property", d: "論理 ブロック終端の角形状", c: "corner-block-end-shape: scoop;" },
  { n: "corner-block-start-shape", k: "property", d: "", c: "corner-block-start-shape: bevel;" },
  { n: "corner-bottom-left-shape", k: "property", d: "", c: "corner-bottom-left-shape: scoop;" },
  { n: "corner-bottom-right-shape", k: "property", d: "", c: "corner-bottom-right-shape: scoop;" },
  { n: "corner-bottom-shape", k: "property", d: "", c: "corner-bottom-shape: bevel;" },
  { n: "corner-end-end-shape", k: "property", d: "", c: "corner-end-end-shape: round;" },
  { n: "corner-end-start-shape", k: "property", d: "", c: "corner-end-start-shape: round;" },
  { n: "corner-inline-end-shape", k: "property", d: "", c: "corner-inline-end-shape: bevel;" },
  { n: "corner-inline-start-shape", k: "property", d: "", c: "corner-inline-start-shape: bevel;" },
  { n: "corner-left-shape", k: "property", d: "", c: "corner-left-shape: scoop;" },
  { n: "corner-right-shape", k: "property", d: "", c: "corner-right-shape: scoop;" },
  { n: "corner-shape", k: "property", d: "角の形状（scoop/bevel 等）", c: "corner-shape: scoop;" },
  { n: "corner-start-end-shape", k: "property", d: "", c: "corner-start-end-shape: round;" },
  { n: "corner-start-start-shape", k: "property", d: "", c: "corner-start-start-shape: round;" },
  { n: "corner-top-left-shape", k: "property", d: "", c: "corner-top-left-shape: scoop;" },
  { n: "corner-top-right-shape", k: "property", d: "", c: "corner-top-right-shape: scoop;" },
  { n: "corner-top-shape", k: "property", d: "", c: "corner-top-shape: bevel;" },
  { n: "cos()", k: "function", d: "余弦", c: "transform: rotate(cos(0)); /* 1 → 1deg */" },
  { n: "counter()", k: "function", d: "カウンタ参照", c: 'content: counter(item) ". ";',
    p: `<style>.ref-cnt{counter-reset:item}.ref-cnt li{list-style:none;counter-increment:item}.ref-cnt li::before{content:counter(item) ". ";color:#6b4423;font-weight:700}</style><ol class="ref-cnt" style="margin:0;padding:0;font-size:.8em"><li>alpha</li><li>beta</li></ol>` },
  { n: "counters()", k: "function", d: "階層化カウンタ", c: 'content: counters(item,".") " ";' },
  { n: "counter-increment", k: "property", d: "カウンタ加算", c: "counter-increment: item;" },
  { n: "counter-reset", k: "property", d: "カウンタ初期化", c: "counter-reset: item 0;" },
  { n: "counter-set", k: "property", d: "カウンタ代入", c: "counter-set: item 10;" },
  { n: "@counter-style", k: "at-rule", d: "独自カウンタ記号", c: "@counter-style circled { system: fixed; symbols: ① ② ③; }" },
  { n: "cross-fade()", k: "function", d: "2画像を混合", c: "background-image: cross-fade(url(a.jpg) 50%, url(b.jpg));" },
  { n: "::cue", k: "pseudo", d: "字幕テキスト", c: "video::cue { color: yellow; }" },
  { n: "cue", k: "property", d: "音声キュー", c: "cue: url(bell.wav);" },
  { n: "cue-after", k: "property", d: "", c: "cue-after: url(b.wav);" },
  { n: "cue-before", k: "property", d: "", c: "cue-before: url(a.wav);" },
  { n: ":current", k: "pseudo", d: "再生中の字幕要素", c: "::cue(:current) { color: yellow; }" },
  { n: "cursor", k: "property", d: "カーソル形状", c: "cursor: pointer;",
    p: `<span style="cursor:pointer;border:1px dashed #aaa;padding:2px 6px">pointer</span>` },
];

/* ----- D ----- */
REF.D = [
  { n: ":default", k: "pseudo", d: "デフォルト選択の要素", c: "option:default { font-weight: bold; }" },
  { n: ":defined", k: "pseudo", d: "定義済みカスタム要素", c: "my-el:defined { display:block; }" },
  { n: "::details-content", k: "pseudo", d: "detailsの開閉部", c: "details::details-content { padding: 1em; }" },
  { n: ":dir()", k: "pseudo", d: "書字方向", c: ":dir(rtl) { text-align: right; }" },
  { n: "direction", k: "property", d: "書字方向", c: "direction: rtl;",
    p: `<div style="direction:rtl;background:#eee;padding:2px 6px">abc 123 def</div>` },
  { n: ":disabled", k: "pseudo", d: "無効状態", c: "input:disabled { opacity: 0.5; }",
    p: `<input type="text" value="入力不可" disabled>` },
  { n: "display", k: "property", d: "表示モード", c: "display: flex;",
    p: `<div style="display:flex;gap:4px"><span style="background:#6b4423;color:#fff;padding:2px 6px">flex</span><span style="background:#6b4423;color:#fff;padding:2px 6px">item</span></div>` },
  { n: "dominant-baseline", k: "property", d: "SVGのベースライン", c: "dominant-baseline: middle;" },
  { n: "drop-shadow()", k: "function", d: "形に沿った影フィルタ", c: "filter: drop-shadow(0 2px 4px #0004);",
    p: `<span style="filter:drop-shadow(0 3px 5px #0005);font-size:1.5em;font-weight:900;color:#6b4423">A</span>` },
  { n: "dynamic-range-limit", k: "property", d: "HDR上限", c: "dynamic-range-limit: standard;" },
];

/* ----- E ----- */
REF.E = [
  { n: "elevation", k: "property", d: "音の高さ(deprecated)", c: "elevation: 45deg;" },
  { n: ":empty", k: "pseudo", d: "中身が空", c: "p:empty { display:none; }" },
  { n: "empty-cells", k: "property", d: "空セルの枠表示", c: "empty-cells: hide;",
    p: `<table style="border-collapse:collapse;empty-cells:hide;font-size:.8em"><tr><td style="border:1px solid #6b4423;padding:2px 6px">A</td><td style="border:1px solid #6b4423;padding:2px 6px"></td></tr></table>` },
  { n: ":enabled", k: "pseudo", d: "有効状態", c: "input:enabled { background: #fff; }" },
  { n: "env()", k: "function", d: "環境変数(safe-area等)", c: "padding-top: env(safe-area-inset-top);" },
  { n: "exp()", k: "function", d: "指数関数", c: "line-height: exp(1);" },
];

/* ----- F ----- */
REF.F = [
  { n: "field-sizing", k: "property", d: "入力欄のサイズ挙動", c: "field-sizing: content;" },
  { n: "::file-selector-button", k: "pseudo", d: "ファイル選択ボタン", c: "::file-selector-button { background: #6b4423; color:#fff; }" },
  { n: "filter", k: "property", d: "フィルタ効果", c: "filter: grayscale(1);",
    p: `<span style="filter:grayscale(1);color:crimson;font-weight:700">灰色化</span>` },
  { n: "filter (IE4-9)", k: "property", d: "旧IE独自", c: "filter: alpha(opacity=50);" },
  { n: ":first-child", k: "pseudo", d: "最初の子", c: "li:first-child { color: crimson; }" },
  { n: "::first-letter", k: "pseudo", d: "最初の一文字", c: "p::first-letter { font-size: 2em; }",
    p: `<span style="font-size:2em;color:#6b4423">あ</span>とがき` },
  { n: "::first-line", k: "pseudo", d: "最初の一行", c: "p::first-line { font-weight: bold; }" },
  { n: ":first-of-type", k: "pseudo", d: "同タイプ中の最初", c: "p:first-of-type { }" },
  { n: "flex", k: "property", d: "flex一括 (grow shrink basis)", c: "flex: 1 1 auto;",
    p: `<div style="display:flex;gap:4px"><span style="flex:1;background:#6b4423;color:#fff;padding:2px 6px;text-align:center">1</span><span style="flex:2;background:#c38;color:#fff;padding:2px 6px;text-align:center">2</span></div>` },
  { n: "flex-basis", k: "property", d: "初期サイズ", c: "flex-basis: 200px;" },
  { n: "flex-direction", k: "property", d: "主軸方向", c: "flex-direction: column;",
    p: `<div style="display:flex;flex-direction:column;gap:2px"><span style="background:#6b4423;color:#fff;padding:1px 6px">A</span><span style="background:#6b4423;color:#fff;padding:1px 6px">B</span></div>` },
  { n: "flex-flow", k: "property", d: "direction+wrap", c: "flex-flow: row wrap;" },
  { n: "flex-grow", k: "property", d: "伸び率", c: "flex-grow: 1;" },
  { n: "flex-shrink", k: "property", d: "縮み率", c: "flex-shrink: 0;" },
  { n: "flex-wrap", k: "property", d: "折り返し", c: "flex-wrap: wrap;",
    p: `<div style="display:flex;flex-wrap:wrap;gap:2px;width:70px"><span style="background:#6b4423;color:#fff;padding:1px 6px">A</span><span style="background:#6b4423;color:#fff;padding:1px 6px">B</span><span style="background:#6b4423;color:#fff;padding:1px 6px">C</span></div>` },
  { n: "float", k: "property", d: "回り込み", c: "float: left;",
    p: `<div style="font-size:.8em"><span style="float:left;width:20px;height:20px;background:#6b4423;margin-right:4px"></span>左浮動テキスト</div>` },
  { n: ":focus", k: "pseudo", d: "フォーカス中", c: ":focus { outline: 2px solid #6b4423; }",
    p: `<input type="text" value="クリック" style="outline:2px solid #6b4423;outline-offset:1px">` },
  { n: ":focus-visible", k: "pseudo", d: "キーボードフォーカス時", c: ":focus-visible { outline: 2px solid; }" },
  { n: ":focus-within", k: "pseudo", d: "子孫にフォーカス", c: "form:focus-within { background:#ffd; }" },
  { n: "font", k: "property", d: "フォント一括", c: "font: 16px/1.5 system-ui;" },
  { n: "@font-face", k: "at-rule", d: "Webフォント定義", c: "@font-face { font-family: X; src: url(x.woff2); }" },
  { n: "font-family", k: "property", d: "書体", c: "font-family: system-ui;",
    p: `<span style="font-family:serif">Serif</span>` },
  { n: "font-feature-settings", k: "property", d: "OpenType機能", c: 'font-feature-settings: "palt";' },
  { n: "@font-feature-values", k: "at-rule", d: "feature命名", c: "@font-feature-values Font { @styleset { alt: 1; } }" },
  { n: "font-kerning", k: "property", d: "カーニング", c: "font-kerning: normal;" },
  { n: "font-language-override", k: "property", d: "言語上書き", c: 'font-language-override: "DEU";' },
  { n: "font-optical-sizing", k: "property", d: "光学サイズ", c: "font-optical-sizing: auto;" },
  { n: "font-palette", k: "property", d: "カラーフォントのパレット", c: "font-palette: --dark;" },
  { n: "@font-palette-values", k: "at-rule", d: "", c: "@font-palette-values --dark { font-family: X; base-palette: 0; }" },
  { n: "font-size", k: "property", d: "文字サイズ", c: "font-size: 18px;",
    p: `<span style="font-size:1.3em">大</span>` },
  { n: "font-size-adjust", k: "property", d: "x-heightによる補正", c: "font-size-adjust: 0.5;" },
  { n: "font-stretch", k: "property", d: "字幅", c: "font-stretch: condensed;",
    p: `<span style="font-stretch:condensed">condensed</span> / <span style="font-stretch:expanded">expanded</span>` },
  { n: "font-style", k: "property", d: "斜体等", c: "font-style: italic;",
    p: `<span style="font-style:italic">italic</span>` },
  { n: "font-synthesis", k: "property", d: "疑似太字/斜体許可", c: "font-synthesis: none;" },
  { n: "font-synthesis-position", k: "property", d: "", c: "font-synthesis-position: none;" },
  { n: "font-synthesis-style", k: "property", d: "", c: "font-synthesis-style: none;" },
  { n: "font-synthesis-small-caps", k: "property", d: "", c: "font-synthesis-small-caps: none;" },
  { n: "font-synthesis-weight", k: "property", d: "", c: "font-synthesis-weight: auto;" },
  { n: "font-variant", k: "property", d: "スモールキャップ等一括", c: "font-variant: small-caps;",
    p: `<span style="font-variant:small-caps">Small Caps</span>` },
  { n: "font-variant-alternates", k: "property", d: "", c: "font-variant-alternates: styleset(alt);" },
  { n: "font-variant-caps", k: "property", d: "", c: "font-variant-caps: small-caps;" },
  { n: "font-variant-east-asian", k: "property", d: "", c: "font-variant-east-asian: jis04;" },
  { n: "font-variant-emoji", k: "property", d: "", c: "font-variant-emoji: emoji;" },
  { n: "font-variant-ligatures", k: "property", d: "", c: "font-variant-ligatures: common-ligatures;" },
  { n: "font-variant-numeric", k: "property", d: "", c: "font-variant-numeric: tabular-nums;" },
  { n: "font-variant-position", k: "property", d: "", c: "font-variant-position: super;" },
  { n: "font-variation-settings", k: "property", d: "可変フォント軸", c: 'font-variation-settings: "wght" 600;' },
  { n: "font-weight", k: "property", d: "太さ", c: "font-weight: 700;",
    p: `<span style="font-weight:900">太</span>` },
  { n: "forced-color-adjust", k: "property", d: "強制カラーモード制御", c: "forced-color-adjust: none;" },
  { n: "<frequency>", k: "type", d: "周波数(Hz/kHz)", c: "pitch: 250Hz;" },
  { n: ":fullscreen", k: "pseudo", d: "全画面中", c: ":fullscreen { background:#000; }" },
  { n: "@function", k: "at-rule", d: "カスタム関数(提案)", c: "@function --sum(--a, --b) { result: calc(var(--a) + var(--b)); }" },
  { n: ":future", k: "pseudo", d: "再生予定の字幕", c: "::cue(:future) { opacity: 0.3; }" },
];

/* ----- G ----- */
REF.G = [
  { n: "gap", k: "property", d: "行列間の隙間", c: "gap: 12px;",
    p: `<div style="display:flex;gap:4px"><span style="background:#6b4423;color:#fff;padding:2px 6px">A</span><span style="background:#6b4423;color:#fff;padding:2px 6px">B</span></div>` },
  { n: "::grammar-error", k: "pseudo", d: "文法エラー強調", c: "::grammar-error { text-decoration: underline wavy green; }" },
  { n: "grayscale()", k: "function", d: "グレースケール", c: "filter: grayscale(1);",
    p: `<span style="filter:grayscale(1);background:linear-gradient(90deg,#c38,#6b4423);color:#fff;padding:2px 6px">gray化</span>` },
  { n: "grid", k: "property", d: "grid一括", c: "grid: auto-flow / 1fr 1fr;",
    p: `<div style="display:grid;grid-template-columns:1fr 1fr;gap:2px;font-size:.75em"><span style="background:#6b4423;color:#fff;padding:1px 4px">A</span><span style="background:#6b4423;color:#fff;padding:1px 4px">B</span><span style="background:#c38;color:#fff;padding:1px 4px">C</span><span style="background:#c38;color:#fff;padding:1px 4px">D</span></div>` },
  { n: "grid-area", k: "property", d: "セルの行/列/name", c: "grid-area: header;" },
  { n: "grid-auto-columns", k: "property", d: "", c: "grid-auto-columns: 100px;" },
  { n: "grid-auto-flow", k: "property", d: "自動配置の流れ", c: "grid-auto-flow: dense;" },
  { n: "grid-auto-rows", k: "property", d: "", c: "grid-auto-rows: 60px;" },
  { n: "grid-column", k: "property", d: "列の開始/終了", c: "grid-column: 1 / 3;" },
  { n: "grid-column-end", k: "property", d: "", c: "grid-column-end: 4;" },
  { n: "grid-column-start", k: "property", d: "", c: "grid-column-start: 1;" },
  { n: "grid-row", k: "property", d: "行の開始/終了", c: "grid-row: 1 / 2;" },
  { n: "grid-row-end", k: "property", d: "", c: "grid-row-end: 3;" },
  { n: "grid-row-start", k: "property", d: "", c: "grid-row-start: 1;" },
  { n: "grid-template", k: "property", d: "grid全体定義", c: "grid-template: 'a b' 1fr / 1fr 2fr;" },
  { n: "grid-template-areas", k: "property", d: "", c: "grid-template-areas: 'h h' 's m';" },
  { n: "grid-template-columns", k: "property", d: "", c: "grid-template-columns: 1fr 2fr;" },
  { n: "grid-template-rows", k: "property", d: "", c: "grid-template-rows: 60px auto;" },
];

/* ----- H ----- */
REF.H = [
  { n: ":has()", k: "pseudo", d: "子孫を持つ要素", c: "article:has(img) { border: 1px solid; }" },
  { n: "height", k: "property", d: "高さ", c: "height: 200px;" },
  { n: "::highlight()", k: "pseudo", d: "カスタムハイライト", c: "::highlight(search) { background: yellow; }" },
  { n: ":hover", k: "pseudo", d: "マウスオーバー", c: "a:hover { color: crimson; }",
    p: `<a style="color:#333" onmouseover="this.style.color='crimson'" onmouseout="this.style.color='#333'">hover</a>` },
  { n: "hsl()", k: "function", d: "HSL色", c: "color: hsl(25, 60%, 40%);" },
  { n: "hsla()", k: "function", d: "HSL+α", c: "color: hsla(25,60%,40%,0.5);" },
  { n: "hue-rotate()", k: "function", d: "色相回転", c: "filter: hue-rotate(90deg);" },
  { n: "hyphenate-character", k: "property", d: "ハイフン記号", c: 'hyphenate-character: "‐";' },
  { n: "hyphenate-limit-chars", k: "property", d: "ハイフネーション最小文字", c: "hyphenate-limit-chars: 6 3 3;" },
  { n: "hyphens", k: "property", d: "改行時ハイフネーション", c: "hyphens: auto;" },
];

/* ----- I ----- */
REF.I = [
  { n: "if()", k: "function", d: "条件分岐(提案)", c: "color: if(dark, white, black);" },
  { n: "<image>", k: "type", d: "画像型", c: "background-image: url(a.jpg);" },
  { n: "image-orientation", k: "property", d: "EXIF回転", c: "image-orientation: from-image;" },
  { n: "image-rendering", k: "property", d: "補間方式", c: "image-rendering: pixelated;" },
  { n: "image-set()", k: "function", d: "解像度別画像", c: "background-image: image-set(url(a.png) 1x, url(a@2x.png) 2x);" },
  { n: "ime-mode", k: "property", d: "IME制御(deprecated)", c: "ime-mode: disabled;" },
  { n: "@import", k: "at-rule", d: "外部CSS読込", c: '@import url("common.css");' },
  { n: "!important", k: "global", d: "優先度最大化", c: "color: red !important;" },
  { n: ":in-range", k: "pseudo", d: "範囲内入力", c: "input:in-range { border-color: green; }" },
  { n: ":indeterminate", k: "pseudo", d: "不定状態", c: "input:indeterminate { outline: 2px dashed; }" },
  { n: "inherit", k: "global", d: "親から継承", c: "color: inherit;" },
  { n: "initial", k: "global", d: "初期値にリセット", c: "color: initial;" },
  { n: "initial-letter", k: "property", d: "ドロップキャップ", c: "initial-letter: 3;" },
  { n: "inline-size", k: "property", d: "論理インライン軸サイズ", c: "inline-size: 80%;" },
  { n: "inset", k: "property", d: "top/right/bottom/left 一括", c: "inset: 0;" },
  { n: "inset-block", k: "property", d: "論理ブロック軸の位置", c: "inset-block: 10px;" },
  { n: "inset-block-end", k: "property", d: "", c: "inset-block-end: 10px;" },
  { n: "inset-block-start", k: "property", d: "", c: "inset-block-start: 10px;" },
  { n: "inset-inline", k: "property", d: "", c: "inset-inline: 10px;" },
  { n: "inset-inline-end", k: "property", d: "", c: "inset-inline-end: 10px;" },
  { n: "inset-inline-start", k: "property", d: "", c: "inset-inline-start: 10px;" },
  { n: "<integer>", k: "type", d: "整数型", c: "z-index: 10;" },
  { n: "interpolate-size", k: "property", d: "autoとの補間", c: "interpolate-size: allow-keywords;" },
  { n: ":invalid", k: "pseudo", d: "不正入力", c: "input:invalid { border-color: crimson; }",
    p: `<input type="email" value="bad" style="border:2px solid crimson">` },
  { n: "invert()", k: "function", d: "色反転フィルター", c: "filter: invert(1);" },
  { n: ":is()", k: "pseudo", d: "マッチのいずれか", c: ":is(h1,h2,h3) { color:#333; }" },
  { n: "isolation", k: "property", d: "合成コンテキスト分離", c: "isolation: isolate;" },
];

/* ----- J ----- */
REF.J = [
  { n: "justify-content", k: "property", d: "主軸整列", c: "justify-content: space-between;",
    p: `<div style="display:flex;justify-content:space-between;background:#eee"><span style="background:#6b4423;color:#fff;padding:2px 6px">A</span><span style="background:#6b4423;color:#fff;padding:2px 6px">B</span></div>` },
  { n: "justify-items", k: "property", d: "gridセル内の主軸整列", c: "justify-items: center;" },
  { n: "justify-self", k: "property", d: "自分だけ上書き", c: "justify-self: end;" },
];

/* ----- K ----- */
REF.K = [
  { n: "@keyframes", k: "at-rule", d: "アニメのキーフレーム定義", c: "@keyframes pulse { 50% { opacity: .5; } }" },
];

/* ----- L ----- */
REF.L = [
  { n: ":lang()", k: "pseudo", d: "言語指定", c: ":lang(ja) { font-family: serif; }" },
  { n: ":last-child", k: "pseudo", d: "最後の子", c: "li:last-child { border:none; }" },
  { n: ":last-of-type", k: "pseudo", d: "同タイプ中の最後", c: "p:last-of-type { }" },
  { n: "@layer", k: "at-rule", d: "カスケードレイヤ", c: "@layer base, theme; @layer base { p { color:#333; } }" },
  { n: "layout-grid", k: "property", d: "IE独自縦書きグリッド", c: "layout-grid: both fixed;" },
  { n: "layout-grid-char", k: "property", d: "IE独自", c: "layout-grid-char: 1em;" },
  { n: "layout-grid-line", k: "property", d: "IE独自", c: "layout-grid-line: 1em;" },
  { n: "layout-grid-mode", k: "property", d: "IE独自", c: "layout-grid-mode: both;" },
  { n: "layout-grid-type", k: "property", d: "IE独自", c: "layout-grid-type: loose;" },
  { n: "left", k: "property", d: "配置位置(左)", c: "left: 10px;" },
  { n: "<length>", k: "type", d: "長さ型(px/em/rem等)", c: "margin: 1em;" },
  { n: "<length-percentage>", k: "type", d: "長さ or %", c: "width: 50%;" },
  { n: "letter-spacing", k: "property", d: "文字間", c: "letter-spacing: 0.1em;",
    p: `<span style="letter-spacing:0.2em">あいうえお</span>` },
  { n: "light-dark()", k: "function", d: "ライト/ダーク切替", c: "color: light-dark(#333, #eee);" },
  { n: "line-break", k: "property", d: "CJK行末の禁則", c: "line-break: strict;" },
  { n: "line-clamp", k: "property", d: "行数で打ち切り", c: "line-clamp: 3;" },
  { n: "line-height", k: "property", d: "行の高さ", c: "line-height: 1.7;" },
  { n: "linear-gradient()", k: "function", d: "線形グラデ", c: "background: linear-gradient(45deg, #c38, #6b4423);",
    p: `<div style="width:60px;height:30px;background:linear-gradient(45deg,#c38,#6b4423)"></div>` },
  { n: ":link", k: "pseudo", d: "未訪問リンク", c: "a:link { color: #06c; }" },
  { n: "list-style", k: "property", d: "リスト一括", c: "list-style: square inside;" },
  { n: "list-style-image", k: "property", d: "", c: "list-style-image: url(x.svg);" },
  { n: "list-style-position", k: "property", d: "", c: "list-style-position: inside;" },
  { n: "list-style-type", k: "property", d: "", c: "list-style-type: decimal-leading-zero;" },
  { n: ":local-link", k: "pseudo", d: "同ドメインリンク", c: "a:local-link { color: green; }" },
];

/* ----- M ----- */
REF.M = [
  { n: "math-depth", k: "property", d: "MathML深度", c: "math-depth: auto-add;" },
  { n: "math-shift", k: "property", d: "MathMLシフト", c: "math-shift: compact;" },
  { n: "math-style", k: "property", d: "MathMLスタイル", c: "math-style: normal;" },
  { n: "matrix()", k: "function", d: "2D変形行列", c: "transform: matrix(1,0,0,1,10,0);" },
  { n: "matrix3d()", k: "function", d: "3D変形行列", c: "transform: matrix3d(...);" },
  { n: "margin", k: "property", d: "外側余白", c: "margin: 16px;" },
  { n: "margin-block", k: "property", d: "論理ブロック軸margin", c: "margin-block: 1em;" },
  { n: "margin-block-end", k: "property", d: "", c: "margin-block-end: 1em;" },
  { n: "margin-block-start", k: "property", d: "", c: "margin-block-start: 1em;" },
  { n: "margin-bottom", k: "property", d: "下余白", c: "margin-bottom: 1em;" },
  { n: "margin-inline", k: "property", d: "論理インライン軸margin", c: "margin-inline: auto;" },
  { n: "margin-inline-end", k: "property", d: "", c: "margin-inline-end: 1em;" },
  { n: "margin-inline-start", k: "property", d: "", c: "margin-inline-start: 1em;" },
  { n: "margin-left", k: "property", d: "左余白", c: "margin-left: auto;" },
  { n: "margin-right", k: "property", d: "右余白", c: "margin-right: auto;" },
  { n: "margin-top", k: "property", d: "上余白", c: "margin-top: 1em;" },
  { n: "::marker", k: "pseudo", d: "リストの印", c: "li::marker { color: crimson; }" },
  { n: "marker-offset", k: "property", d: "印との間隔", c: "marker-offset: 1em;" },
  { n: "marks", k: "property", d: "印刷のトンボ", c: "marks: crop cross;" },
  { n: "mask", k: "property", d: "マスクの一括", c: "mask: url(m.svg) center/cover;" },
  { n: "mask-clip", k: "property", d: "", c: "mask-clip: border-box;" },
  { n: "mask-composite", k: "property", d: "", c: "mask-composite: exclude;" },
  { n: "mask-image", k: "property", d: "", c: "mask-image: url(m.svg);" },
  { n: "mask-mode", k: "property", d: "", c: "mask-mode: luminance;" },
  { n: "mask-origin", k: "property", d: "", c: "mask-origin: padding-box;" },
  { n: "mask-position", k: "property", d: "", c: "mask-position: center;" },
  { n: "mask-repeat", k: "property", d: "", c: "mask-repeat: no-repeat;" },
  { n: "mask-size", k: "property", d: "", c: "mask-size: contain;" },
  { n: "max()", k: "function", d: "最大値", c: "width: max(400px, 50%);" },
  { n: "max-block-size", k: "property", d: "論理最大高", c: "max-block-size: 100vh;" },
  { n: "max-height", k: "property", d: "最大高", c: "max-height: 80vh;" },
  { n: "max-inline-size", k: "property", d: "論理最大幅", c: "max-inline-size: 60ch;" },
  { n: "max-width", k: "property", d: "最大幅", c: "max-width: 800px;" },
  { n: "@media", k: "at-rule", d: "メディアクエリ", c: "@media (max-width: 600px) { body { font-size: 14px; } }" },
  { n: "min()", k: "function", d: "最小値", c: "width: min(800px, 100%);" },
  { n: "min-block-size", k: "property", d: "論理最小高", c: "min-block-size: 0;" },
  { n: "min-height", k: "property", d: "最小高", c: "min-height: 100vh;" },
  { n: "min-inline-size", k: "property", d: "論理最小幅", c: "min-inline-size: 200px;" },
  { n: "min-width", k: "property", d: "最小幅", c: "min-width: 320px;" },
  { n: "mix-blend-mode", k: "property", d: "要素同士の合成", c: "mix-blend-mode: multiply;" },
  { n: "mod()", k: "function", d: "剰余", c: "rotate: mod(400deg, 360deg);" },
  { n: ":modal", k: "pseudo", d: "モーダル中", c: "dialog:modal { box-shadow: 0 0 20px #0005; }" },
];

/* ----- N ----- */
REF.N = [
  { n: "@namespace", k: "at-rule", d: "名前空間宣言", c: '@namespace svg url("http://www.w3.org/2000/svg");' },
  { n: ":not()", k: "pseudo", d: "否定", c: "li:not(.active) { opacity: 0.6; }" },
  { n: ":nth-child(n)", k: "pseudo", d: "n番目の子", c: "li:nth-child(odd) { background: #eee; }" },
  { n: ":nth-col", k: "pseudo", d: "表のn番目の列", c: "td:nth-col(2) { background:#ffd; }" },
  { n: ":nth-last-child(n)", k: "pseudo", d: "末尾からn番目の子", c: "li:nth-last-child(1) { border:none; }" },
  { n: ":nth-last-col", k: "pseudo", d: "末尾からn番目の列", c: "td:nth-last-col(1) { color: crimson; }" },
  { n: ":nth-last-of-type(n)", k: "pseudo", d: "末尾からn番目(同タイプ)", c: "p:nth-last-of-type(1) { }" },
  { n: ":nth-of-type(n)", k: "pseudo", d: "n番目(同タイプ)", c: "p:nth-of-type(2n) { }" },
  { n: "<number>", k: "type", d: "数値型", c: "opacity: 0.5;" },
];

/* ----- O ----- */
REF.O = [
  { n: "object-fit", k: "property", d: "画像のフィット", c: "object-fit: cover;" },
  { n: "object-position", k: "property", d: "画像の位置", c: "object-position: center;" },
  { n: "offset", k: "property", d: "motion pathの一括", c: "offset: path('M 0 0 L 100 0') 50%;" },
  { n: "offset-anchor", k: "property", d: "motion pathの基点", c: "offset-anchor: center;" },
  { n: "offset-distance", k: "property", d: "", c: "offset-distance: 50%;" },
  { n: "offset-path", k: "property", d: "", c: "offset-path: path('M 0 0 L 100 0');" },
  { n: "offset-position", k: "property", d: "", c: "offset-position: 0 0;" },
  { n: "offset-rotate", k: "property", d: "", c: "offset-rotate: auto;" },
  { n: ":only-child", k: "pseudo", d: "唯一の子", c: "li:only-child { font-style:italic; }" },
  { n: ":only-of-type", k: "pseudo", d: "同タイプ中 唯一", c: "p:only-of-type { }" },
  { n: "opacity", k: "property", d: "不透明度", c: "opacity: 0.5;",
    p: `<span style="opacity:0.4">半透明</span>` },
  { n: "opacity()", k: "function", d: "filterの不透明度", c: "filter: opacity(0.5);" },
  { n: ":open", k: "pseudo", d: "details/dialog 開", c: "details:open { background:#ffd; }" },
  { n: ":optional", k: "pseudo", d: "必須でない", c: "input:optional { }" },
  { n: "order", k: "property", d: "flex/grid順序", c: "order: 2;" },
  { n: "orphans", k: "property", d: "改ページ時 先頭最小行数", c: "orphans: 3;" },
  { n: ":out-of-range", k: "pseudo", d: "範囲外入力", c: "input:out-of-range { border: 2px solid crimson; }" },
  { n: "outline", k: "property", d: "アウトライン", c: "outline: 2px solid #6b4423;",
    p: `<span style="outline:2px solid #6b4423;padding:2px 6px">枠</span>` },
  { n: "outline-color", k: "property", d: "", c: "outline-color: red;" },
  { n: "outline-offset", k: "property", d: "枠までの距離", c: "outline-offset: 4px;" },
  { n: "outline-style", k: "property", d: "", c: "outline-style: dashed;" },
  { n: "outline-width", k: "property", d: "", c: "outline-width: 2px;" },
  { n: "overflow", k: "property", d: "はみ出し処理", c: "overflow: auto;" },
  { n: "overflow-anchor", k: "property", d: "アンカー固定", c: "overflow-anchor: none;" },
  { n: "overflow-block", k: "property", d: "", c: "overflow-block: auto;" },
  { n: "overflow-clip-margin", k: "property", d: "", c: "overflow-clip-margin: 8px;" },
  { n: "overflow-inline", k: "property", d: "", c: "overflow-inline: auto;" },
  { n: "overflow-wrap", k: "property", d: "長い語の折り返し", c: "overflow-wrap: anywhere;" },
  { n: "overflow-x", k: "property", d: "", c: "overflow-x: auto;" },
  { n: "overflow-y", k: "property", d: "", c: "overflow-y: scroll;" },
  { n: "overscroll-behavior", k: "property", d: "スクロール到達時の伝播", c: "overscroll-behavior: contain;" },
  { n: "overscroll-behavior-block", k: "property", d: "", c: "overscroll-behavior-block: contain;" },
  { n: "overscroll-behavior-inline", k: "property", d: "", c: "overscroll-behavior-inline: auto;" },
  { n: "overlay", k: "property", d: "top-layerの挙動", c: "overlay: auto;" },
  { n: "overscroll-behavior-x", k: "property", d: "", c: "overscroll-behavior-x: contain;" },
  { n: "overscroll-behavior-y", k: "property", d: "", c: "overscroll-behavior-y: none;" },
];

/* ----- P ----- */
REF.P = [
  { n: "padding", k: "property", d: "内側余白", c: "padding: 16px;" },
  { n: "padding-block", k: "property", d: "論理ブロック軸", c: "padding-block: 1em;" },
  { n: "padding-block-end", k: "property", d: "", c: "padding-block-end: 1em;" },
  { n: "padding-block-start", k: "property", d: "", c: "padding-block-start: 1em;" },
  { n: "padding-bottom", k: "property", d: "", c: "padding-bottom: 1em;" },
  { n: "padding-inline", k: "property", d: "論理インライン軸", c: "padding-inline: 1em;" },
  { n: "padding-inline-end", k: "property", d: "", c: "padding-inline-end: 1em;" },
  { n: "padding-inline-start", k: "property", d: "", c: "padding-inline-start: 1em;" },
  { n: "padding-left", k: "property", d: "", c: "padding-left: 1em;" },
  { n: "padding-right", k: "property", d: "", c: "padding-right: 1em;" },
  { n: "padding-top", k: "property", d: "", c: "padding-top: 1em;" },
  { n: "@page", k: "at-rule", d: "印刷ページ設定", c: "@page { margin: 2cm; }" },
  { n: "page", k: "property", d: "ページ名参照", c: "page: cover;" },
  { n: "page-break-after", k: "property", d: "旧仕様：要素後で改ページ", c: "page-break-after: always;" },
  { n: "page-break-before", k: "property", d: "旧仕様：要素前で改ページ", c: "page-break-before: always;" },
  { n: "page-break-inside", k: "property", d: "旧仕様：要素内改ページ禁止", c: "page-break-inside: avoid;" },
  { n: "paint()", k: "function", d: "Paint API参照", c: "background-image: paint(myShape);" },
  { n: "::part()", k: "pseudo", d: "shadow partを外から指定", c: "my-el::part(label) { color: crimson; }" },
  { n: ":past", k: "pseudo", d: "再生済みの字幕", c: "::cue(:past) { opacity: 0.5; }" },
  { n: "pause", k: "property", d: "音声一時停止", c: "pause: 100ms;" },
  { n: "pause-after", k: "property", d: "", c: "pause-after: 100ms;" },
  { n: "pause-before", k: "property", d: "", c: "pause-before: 100ms;" },
  { n: ":paused", k: "pseudo", d: "一時停止中", c: "audio:paused { opacity: 0.5; }" },
  { n: "<percentage>", k: "type", d: "%型", c: "width: 50%;" },
  { n: "perspective", k: "property", d: "3D視点距離", c: "perspective: 600px;" },
  { n: "perspective()", k: "function", d: "transformで遠近", c: "transform: perspective(600px) rotateY(20deg);" },
  { n: "perspective-origin", k: "property", d: "視点の原点", c: "perspective-origin: 50% 50%;" },
  { n: ":picture-in-picture", k: "pseudo", d: "PiP中", c: "video:picture-in-picture { outline: 2px solid crimson; }" },
  { n: "pitch", k: "property", d: "声の高さ", c: "pitch: medium;" },
  { n: "pitch-range", k: "property", d: "抑揚幅", c: "pitch-range: 50;" },
  { n: "place-content", k: "property", d: "align + justify content", c: "place-content: center;" },
  { n: "place-items", k: "property", d: "align + justify items", c: "place-items: center;" },
  { n: "place-self", k: "property", d: "align + justify self", c: "place-self: center;" },
  { n: "::placeholder", k: "pseudo", d: "プレースホルダ文字", c: "::placeholder { color:#bbb; }",
    p: `<input placeholder="入力…">` },
  { n: ":placeholder-shown", k: "pseudo", d: "プレースホルダ表示中", c: "input:placeholder-shown { font-style: italic; }" },
  { n: "play-during", k: "property", d: "発話中のBGM", c: "play-during: url(bgm.wav);" },
  { n: ":playing", k: "pseudo", d: "再生中", c: "audio:playing { }" },
  { n: "pointer-events", k: "property", d: "クリック反応制御", c: "pointer-events: none;" },
  { n: "position", k: "property", d: "配置方式", c: "position: sticky;" },
  { n: "<position>", k: "type", d: "位置型(50% 50% 等)", c: "background-position: 50% 50%;" },
  { n: "position-anchor", k: "property", d: "アンカー参照", c: "position-anchor: --btn;" },
  { n: "position-area", k: "property", d: "アンカーのエリア指定", c: "position-area: top;" },
  { n: "position-try", k: "property", d: "アンカー位置のフォールバック", c: "position-try: --flip;" },
  { n: "@position-try", k: "at-rule", d: "代替位置の定義", c: "@position-try --flip { top: auto; bottom: 0; }" },
  { n: "position-try-fallbacks", k: "property", d: "", c: "position-try-fallbacks: --flip;" },
  { n: "position-try-order", k: "property", d: "", c: "position-try-order: most-height;" },
  { n: "position-visibility", k: "property", d: "アンカー可視時のみ表示", c: "position-visibility: anchors-visible;" },
  { n: "pow()", k: "function", d: "べき乗", c: "width: calc(pow(2, 10) * 1px);" },
  { n: "print-color-adjust", k: "property", d: "印刷時の色調整", c: "print-color-adjust: exact;" },
  { n: "@property", k: "at-rule", d: "カスタム変数の型宣言", c: "@property --hue { syntax: '<angle>'; inherits: false; initial-value: 0deg; }" },
  { n: "progress()", k: "function", d: "区間内の進捗値", c: "opacity: progress(100px, 0px, 200px);" },
];

/* ----- Q ----- */
REF.Q = [
  { n: "quotes", k: "property", d: "引用符", c: 'quotes: "「" "」";' },
];

/* ----- R ----- */
REF.R = [
  { n: "radial-gradient()", k: "function", d: "放射状グラデ", c: "background: radial-gradient(circle, #fff, #6b4423);",
    p: `<div style="width:40px;height:40px;background:radial-gradient(circle,#fff,#6b4423);border-radius:50%"></div>` },
  { n: ":read-only", k: "pseudo", d: "読取専用", c: "input:read-only { background:#eee; }" },
  { n: ":read-write", k: "pseudo", d: "編集可", c: "input:read-write { }" },
  { n: "reading-flow", k: "property", d: "読み順", c: "reading-flow: source-order;" },
  { n: "reading-order", k: "property", d: "", c: "reading-order: 2;" },
  { n: "rem()", k: "function", d: "除算剰余", c: "rotate: rem(400deg, 360deg);" },
  { n: "repeating-conic-gradient()", k: "function", d: "繰り返し円錐", c: "background: repeating-conic-gradient(#fff 0 10deg,#6b4423 0 20deg);" },
  { n: "repeating-linear-gradient()", k: "function", d: "繰り返し線形", c: "background: repeating-linear-gradient(45deg,#fff 0 10px,#6b4423 0 20px);",
    p: `<div style="width:60px;height:30px;background:repeating-linear-gradient(45deg,#fff 0 8px,#6b4423 0 16px)"></div>` },
  { n: "repeating-radial-gradient()", k: "function", d: "繰り返し放射", c: "background: repeating-radial-gradient(circle,#fff 0 5px,#6b4423 0 10px);" },
  { n: ":required", k: "pseudo", d: "必須入力", c: "input:required { border-color: crimson; }" },
  { n: "resize", k: "property", d: "ユーザーリサイズ許可", c: "resize: both;" },
  { n: "<resolution>", k: "type", d: "解像度型(dpi/dppx)", c: "@media (min-resolution: 2dppx) { }" },
  { n: "revert", k: "global", d: "ユーザーエージェント値に戻す", c: "all: revert;" },
  { n: "rgb()", k: "function", d: "RGB色", c: "color: rgb(107 68 35);" },
  { n: "rgba()", k: "function", d: "RGB+α", c: "color: rgba(107,68,35,0.5);" },
  { n: "richness", k: "property", d: "声の豊かさ", c: "richness: 50;" },
  { n: "right", k: "property", d: "配置位置(右)", c: "right: 10px;" },
  { n: ":root", k: "pseudo", d: "ルート要素(通常html)", c: ":root { --accent: crimson; }" },
  { n: "rotate", k: "property", d: "独立回転プロパティ", c: "rotate: 15deg;",
    p: `<div style="display:inline-block;padding:2px 6px;background:#6b4423;color:#fff;rotate:15deg">rot</div>` },
  { n: "rotate()", k: "function", d: "transformで回転", c: "transform: rotate(45deg);" },
  { n: "rotate3d()", k: "function", d: "3D回転", c: "transform: rotate3d(1,1,0,45deg);" },
  { n: "rotateX()", k: "function", d: "X軸回転", c: "transform: rotateX(30deg);" },
  { n: "rotateY()", k: "function", d: "Y軸回転", c: "transform: rotateY(30deg);" },
  { n: "rotateZ()", k: "function", d: "Z軸回転", c: "transform: rotateZ(30deg);" },
  { n: "round()", k: "function", d: "丸め", c: "width: round(107px, 10px);" },
  { n: "row-gap", k: "property", d: "行の隙間", c: "row-gap: 12px;" },
  { n: "ruby-align", k: "property", d: "ルビの揃え", c: "ruby-align: center;" },
  { n: "ruby-overhang", k: "property", d: "ルビはみ出し許可", c: "ruby-overhang: auto;" },
  { n: "ruby-position", k: "property", d: "ルビ位置", c: "ruby-position: over;" },
];

/* ----- S ----- */
REF.S = [
  { n: "saturate()", k: "function", d: "彩度フィルタ", c: "filter: saturate(2);" },
  { n: "scale", k: "property", d: "独立拡大縮小", c: "scale: 1.5;" },
  { n: "scale()", k: "function", d: "transformで拡大縮小", c: "transform: scale(1.5);" },
  { n: "scale3d()", k: "function", d: "3D拡大縮小", c: "transform: scale3d(1,1.5,1);" },
  { n: "scaleX()", k: "function", d: "", c: "transform: scaleX(2);" },
  { n: "scaleY()", k: "function", d: "", c: "transform: scaleY(2);" },
  { n: "scaleZ()", k: "function", d: "", c: "transform: scaleZ(2);" },
  { n: ":scope", k: "pseudo", d: "スコープ内のルート", c: ":scope > li { }" },
  { n: "@scope", k: "at-rule", d: "スコープ付きルール", c: "@scope (.card) { h1 { color: crimson; } }" },
  { n: "scroll-behavior", k: "property", d: "スクロールの滑らかさ", c: "scroll-behavior: smooth;" },
  { n: "::scroll-button(direction)", k: "pseudo", d: "スクロールボタン", c: "::scroll-button(right) { }" },
  { n: "scroll-margin", k: "property", d: "snapマージン", c: "scroll-margin: 20px;" },
  { n: "scroll-margin-block", k: "property", d: "", c: "scroll-margin-block: 20px;" },
  { n: "scroll-margin-block-end", k: "property", d: "", c: "scroll-margin-block-end: 20px;" },
  { n: "scroll-margin-block-start", k: "property", d: "", c: "scroll-margin-block-start: 20px;" },
  { n: "scroll-margin-bottom", k: "property", d: "", c: "scroll-margin-bottom: 20px;" },
  { n: "scroll-margin-inline", k: "property", d: "", c: "scroll-margin-inline: 20px;" },
  { n: "scroll-margin-inline-end", k: "property", d: "", c: "scroll-margin-inline-end: 20px;" },
  { n: "scroll-margin-inline-start", k: "property", d: "", c: "scroll-margin-inline-start: 20px;" },
  { n: "scroll-margin-left", k: "property", d: "", c: "scroll-margin-left: 20px;" },
  { n: "scroll-margin-right", k: "property", d: "", c: "scroll-margin-right: 20px;" },
  { n: "scroll-margin-top", k: "property", d: "", c: "scroll-margin-top: 20px;" },
  { n: "::scroll-marker-group", k: "pseudo", d: "スクロールマーカー一覧", c: "::scroll-marker-group { }" },
  { n: "scroll-marker-group", k: "property", d: "", c: "scroll-marker-group: after;" },
  { n: "::scroll-marker", k: "pseudo", d: "スクロールマーカー", c: "::scroll-marker { background:#6b4423; }" },
  { n: "scroll-padding", k: "property", d: "スクロールコンテナのパディング", c: "scroll-padding: 80px;" },
  { n: "scroll-padding-block", k: "property", d: "", c: "scroll-padding-block: 80px;" },
  { n: "scroll-padding-block-end", k: "property", d: "", c: "scroll-padding-block-end: 80px;" },
  { n: "scroll-padding-block-start", k: "property", d: "", c: "scroll-padding-block-start: 80px;" },
  { n: "scroll-padding-bottom", k: "property", d: "", c: "scroll-padding-bottom: 80px;" },
  { n: "scroll-padding-inline", k: "property", d: "", c: "scroll-padding-inline: 20px;" },
  { n: "scroll-padding-inline-end", k: "property", d: "", c: "scroll-padding-inline-end: 20px;" },
  { n: "scroll-padding-inline-start", k: "property", d: "", c: "scroll-padding-inline-start: 20px;" },
  { n: "scroll-padding-left", k: "property", d: "", c: "scroll-padding-left: 20px;" },
  { n: "scroll-padding-right", k: "property", d: "", c: "scroll-padding-right: 20px;" },
  { n: "scroll-padding-top", k: "property", d: "", c: "scroll-padding-top: 80px;" },
  { n: "scroll-snap-align", k: "property", d: "snap位置", c: "scroll-snap-align: start;" },
  { n: "scroll-snap-stop", k: "property", d: "snap停止挙動", c: "scroll-snap-stop: always;" },
  { n: "scroll-snap-type", k: "property", d: "snapの種類", c: "scroll-snap-type: x mandatory;" },
  { n: "scroll-target-group", k: "property", d: "", c: "scroll-target-group: auto;" },
  { n: "scroll-timeline", k: "property", d: "スクロール駆動", c: "scroll-timeline: --t block;" },
  { n: "scroll-timeline-axis", k: "property", d: "", c: "scroll-timeline-axis: block;" },
  { n: "scroll-timeline-name", k: "property", d: "", c: "scroll-timeline-name: --t;" },
  { n: "scrollbar-3dlight-color", k: "property", d: "旧IE", c: "scrollbar-3dlight-color: #ccc;" },
  { n: "scrollbar-arrow-color", k: "property", d: "旧IE", c: "scrollbar-arrow-color: #6b4423;" },
  { n: "scrollbar-base-color", k: "property", d: "旧IE", c: "scrollbar-base-color: #eee;" },
  { n: "scrollbar-color", k: "property", d: "バー色(親指/軌道)", c: "scrollbar-color: #6b4423 #eee;" },
  { n: "scrollbar-darkshadow-color", k: "property", d: "旧IE", c: "scrollbar-darkshadow-color: #333;" },
  { n: "scrollbar-face-color", k: "property", d: "旧IE", c: "scrollbar-face-color: #6b4423;" },
  { n: "scrollbar-gutter", k: "property", d: "バー領域の予約", c: "scrollbar-gutter: stable;" },
  { n: "scrollbar-highlight-color", k: "property", d: "旧IE", c: "scrollbar-highlight-color: #fff;" },
  { n: "scrollbar-shadow-color", k: "property", d: "旧IE", c: "scrollbar-shadow-color: #333;" },
  { n: "scrollbar-track-color", k: "property", d: "旧IE", c: "scrollbar-track-color: #eee;" },
  { n: "scrollbar-width", k: "property", d: "バー幅", c: "scrollbar-width: thin;" },
  { n: "::search-text", k: "pseudo", d: "検索結果のテキスト", c: "::search-text { background:yellow; }" },
  { n: "::selection", k: "pseudo", d: "選択範囲", c: "::selection { background: #6b4423; color:#fff; }" },
  { n: "sepia()", k: "function", d: "セピア調", c: "filter: sepia(1);" },
  { n: "shape()", k: "function", d: "図形パス", c: "clip-path: shape(from 0 0, line to 100% 100%);" },
  { n: "shape-outside", k: "property", d: "テキスト回り込みの形", c: "shape-outside: circle(50%);" },
  { n: "shape-margin", k: "property", d: "shape-outsideの余白", c: "shape-margin: 1em;" },
  { n: "shape-image-threshold", k: "property", d: "透過画像の閾値", c: "shape-image-threshold: 0.5;" },
  { n: "sibling-count()", k: "function", d: "兄弟数", c: "--n: sibling-count();" },
  { n: "sibling-index()", k: "function", d: "兄弟中の位置", c: "--i: sibling-index();" },
  { n: "sign()", k: "function", d: "符号", c: "x: sign(-5); /* -1 */" },
  { n: "sin()", k: "function", d: "正弦", c: "x: sin(30deg);" },
  { n: "size", k: "property", d: "@page用サイズ", c: "size: A4 landscape;" },
  { n: "skew()", k: "function", d: "skew変形", c: "transform: skew(10deg, 5deg);" },
  { n: "skewX()", k: "function", d: "", c: "transform: skewX(10deg);" },
  { n: "skewY()", k: "function", d: "", c: "transform: skewY(5deg);" },
  { n: "::slotted()", k: "pseudo", d: "shadow内のslot要素", c: "::slotted(span) { color: crimson; }" },
  { n: "speak", k: "property", d: "読み上げ制御", c: "speak: none;" },
  { n: "speak-header", k: "property", d: "表ヘッダ読み上げ", c: "speak-header: always;" },
  { n: "speak-numeral", k: "property", d: "数字読み上げ", c: "speak-numeral: digits;" },
  { n: "speak-punctuation", k: "property", d: "句読点読み上げ", c: "speak-punctuation: code;" },
  { n: "speech-rate", k: "property", d: "読み上げ速度", c: "speech-rate: medium;" },
  { n: "::spelling-error", k: "pseudo", d: "スペル誤り強調", c: "::spelling-error { text-decoration: underline wavy red; }" },
  { n: "@starting-style", k: "at-rule", d: "出現時の初期スタイル", c: "@starting-style { .m { opacity: 0; } }" },
  { n: "stress", k: "property", d: "強勢", c: "stress: 50;" },
  { n: "<string>", k: "type", d: "文字列型", c: 'content: "hello";' },
  { n: "@supports", k: "at-rule", d: "機能クエリ", c: "@supports (display: grid) { }" },
];

/* ----- T ----- */
REF.T = [
  { n: "tab-size", k: "property", d: "tab文字幅", c: "tab-size: 4;" },
  { n: "table-layout", k: "property", d: "表レイアウトアルゴリズム", c: "table-layout: fixed;" },
  { n: "tan()", k: "function", d: "正接", c: "x: tan(45deg);" },
  { n: ":target", k: "pseudo", d: "URL#で対象の要素", c: ":target { background: yellow; }" },
  { n: ":target-current", k: "pseudo", d: "ターゲットの現在位置", c: ":target-current { outline: 2px solid; }" },
  { n: "::target-text", k: "pseudo", d: "テキストフラグメント", c: "::target-text { background: yellow; }" },
  { n: ":target-within", k: "pseudo", d: "内部にtargetを含む", c: "section:target-within { outline: 2px solid; }" },
  { n: "text-align", k: "property", d: "横整列", c: "text-align: center;",
    p: `<div style="text-align:center;border:1px dashed #ccc">中央</div>` },
  { n: "text-align-last", k: "property", d: "最終行整列", c: "text-align-last: justify;" },
  { n: "text-autospace", k: "property", d: "CJK/英数字間の空白", c: "text-autospace: normal;" },
  { n: "text-box", k: "property", d: "text-box-trim+edge一括", c: "text-box: trim-both cap alphabetic;" },
  { n: "text-box-edge", k: "property", d: "", c: "text-box-edge: cap alphabetic;" },
  { n: "text-box-trim", k: "property", d: "字上下の空白を削る", c: "text-box-trim: both;" },
  { n: "text-combine-upright", k: "property", d: "縦中横", c: "text-combine-upright: all;" },
  { n: "text-decoration", k: "property", d: "装飾一括", c: "text-decoration: underline wavy crimson;",
    p: `<span style="text-decoration:underline wavy crimson">波線</span>` },
  { n: "text-decoration-color", k: "property", d: "", c: "text-decoration-color: crimson;" },
  { n: "text-decoration-line", k: "property", d: "", c: "text-decoration-line: line-through;" },
  { n: "text-decoration-skip", k: "property", d: "", c: "text-decoration-skip: objects;" },
  { n: "text-decoration-skip-ink", k: "property", d: "下線が字を避ける", c: "text-decoration-skip-ink: auto;" },
  { n: "text-decoration-style", k: "property", d: "", c: "text-decoration-style: dashed;" },
  { n: "text-decoration-thickness", k: "property", d: "", c: "text-decoration-thickness: 3px;" },
  { n: "text-emphasis", k: "property", d: "傍点", c: 'text-emphasis: "●" crimson;',
    p: `<span style="-webkit-text-emphasis:'●' crimson;text-emphasis:'●' crimson">傍点</span>` },
  { n: "text-emphasis-color", k: "property", d: "", c: "text-emphasis-color: crimson;" },
  { n: "text-emphasis-position", k: "property", d: "", c: "text-emphasis-position: over;" },
  { n: "text-emphasis-style", k: "property", d: "", c: 'text-emphasis-style: "●";' },
  { n: "text-indent", k: "property", d: "字下げ", c: "text-indent: 1em;" },
  { n: "text-justify", k: "property", d: "両端揃えアルゴ", c: "text-justify: inter-character;" },
  { n: "text-kashida-space", k: "property", d: "アラビア語の伸長", c: "text-kashida-space: 50%;" },
  { n: "text-orientation", k: "property", d: "縦書き時の字の向き", c: "text-orientation: upright;" },
  { n: "text-overflow", k: "property", d: "はみ出し処理", c: "text-overflow: ellipsis;",
    p: `<div style="width:90px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">長い文字列を省略します</div>` },
  { n: "text-rendering", k: "property", d: "描画最適化", c: "text-rendering: optimizeLegibility;" },
  { n: "text-shadow", k: "property", d: "文字影", c: "text-shadow: 1px 1px 2px #0004;",
    p: `<span style="text-shadow:1px 1px 2px #0008;font-weight:700">Shadow</span>` },
  { n: "text-size-adjust", k: "property", d: "モバイル自動拡大", c: "text-size-adjust: 100%;" },
  { n: "text-spacing-trim", k: "property", d: "行頭行末の約物詰め", c: "text-spacing-trim: trim-start;" },
  { n: "text-stroke", k: "property", d: "文字縁取り(一括)", c: "-webkit-text-stroke: 1px crimson;" },
  { n: "text-stroke-color", k: "property", d: "", c: "-webkit-text-stroke-color: crimson;" },
  { n: "text-stroke-width", k: "property", d: "", c: "-webkit-text-stroke-width: 1px;" },
  { n: "text-transform", k: "property", d: "大小文字変換", c: "text-transform: uppercase;",
    p: `<span style="text-transform:uppercase">abc</span>` },
  { n: "text-underline-offset", k: "property", d: "下線の位置", c: "text-underline-offset: 3px;" },
  { n: "text-underline-position", k: "property", d: "下線位置モード", c: "text-underline-position: under;" },
  { n: "text-wrap", k: "property", d: "改行アルゴ一括", c: "text-wrap: balance;" },
  { n: "text-wrap-mode", k: "property", d: "", c: "text-wrap-mode: wrap;" },
  { n: "text-wrap-style", k: "property", d: "balance/pretty", c: "text-wrap-style: balance;" },
  { n: "<time>", k: "type", d: "時間型", c: "transition-duration: 0.3s;" },
  { n: "timeline-scope", k: "property", d: "timeline共有", c: "timeline-scope: --t;" },
  { n: "timeline-trigger", k: "property", d: "timelineトリガ", c: "timeline-trigger: --t;" },
  { n: "timeline-trigger-activation-range", k: "property", d: "", c: "timeline-trigger-activation-range: cover;" },
  { n: "timeline-trigger-activation-range-end", k: "property", d: "", c: "timeline-trigger-activation-range-end: 100%;" },
  { n: "timeline-trigger-activation-range-start", k: "property", d: "", c: "timeline-trigger-activation-range-start: 0%;" },
  { n: "timeline-trigger-active-range", k: "property", d: "", c: "timeline-trigger-active-range: cover;" },
  { n: "timeline-trigger-active-range-end", k: "property", d: "", c: "timeline-trigger-active-range-end: 100%;" },
  { n: "timeline-trigger-active-range-start", k: "property", d: "", c: "timeline-trigger-active-range-start: 0%;" },
  { n: "timeline-trigger-name", k: "property", d: "", c: "timeline-trigger-name: --t;" },
  { n: "timeline-trigger-source", k: "property", d: "", c: "timeline-trigger-source: scroll();" },
  { n: "toggle()", k: "function", d: "値のトグル", c: "list-style-type: toggle(disc, circle);" },
  { n: "top", k: "property", d: "配置位置(上)", c: "top: 10px;" },
  { n: "touch-action", k: "property", d: "タッチ操作制御", c: "touch-action: pan-y;" },
  { n: "transform", k: "property", d: "変形", c: "transform: rotate(5deg) scale(1.1);" },
  { n: "transform-box", k: "property", d: "変形の基準箱", c: "transform-box: fill-box;" },
  { n: "transform-origin", k: "property", d: "変形の原点", c: "transform-origin: top left;" },
  { n: "transform-style", k: "property", d: "3D維持", c: "transform-style: preserve-3d;" },
  { n: "transition", k: "property", d: "トランジション一括", c: "transition: color .3s;",
    p: `<a style="color:#333;transition:color .3s" onmouseover="this.style.color='crimson'" onmouseout="this.style.color='#333'">ゆっくり色変化</a>` },
  { n: "transition-delay", k: "property", d: "", c: "transition-delay: 100ms;" },
  { n: "transition-duration", k: "property", d: "", c: "transition-duration: 0.3s;" },
  { n: "transition-property", k: "property", d: "", c: "transition-property: transform;" },
  { n: "transition-timing-function", k: "property", d: "", c: "transition-timing-function: ease-in-out;" },
  { n: "translate", k: "property", d: "独立移動", c: "translate: 10px 0;" },
  { n: "translate()", k: "function", d: "", c: "transform: translate(10px, 0);" },
  { n: "translate3d()", k: "function", d: "", c: "transform: translate3d(0,0,10px);" },
  { n: "translateX()", k: "function", d: "", c: "transform: translateX(10px);" },
  { n: "translateY()", k: "function", d: "", c: "transform: translateY(10px);" },
  { n: "translateZ()", k: "function", d: "", c: "transform: translateZ(10px);" },
  { n: "trigger-scope", k: "property", d: "triggerの共有範囲", c: "trigger-scope: all;" },
];

/* ----- U ----- */
REF.U = [
  { n: "unicode-bidi", k: "property", d: "双方向アルゴ制御", c: "unicode-bidi: bidi-override;" },
  { n: "unset", k: "global", d: "inherit or initial", c: "color: unset;" },
  { n: "<url>", k: "type", d: "URL型", c: "background-image: url(a.jpg);" },
  { n: "url()", k: "function", d: "URL参照", c: 'background: url("a.jpg");' },
  { n: ":user-invalid", k: "pseudo", d: "ユーザー操作後の不正", c: "input:user-invalid { border: 2px solid crimson; }" },
  { n: "user-select", k: "property", d: "テキスト選択制御", c: "user-select: none;" },
  { n: ":user-valid", k: "pseudo", d: "ユーザー操作後の正常", c: "input:user-valid { border-color: green; }" },
];

/* ----- V ----- */
REF.V = [
  { n: ":valid", k: "pseudo", d: "入力妥当", c: "input:valid { border-color: green; }" },
  { n: "var()", k: "function", d: "カスタム変数参照", c: "color: var(--accent, crimson);" },
  { n: "vertical-align", k: "property", d: "インライン縦整列", c: "vertical-align: middle;" },
  { n: "view-timeline", k: "property", d: "ビュー駆動", c: "view-timeline: --v block;" },
  { n: "view-timeline-axis", k: "property", d: "", c: "view-timeline-axis: block;" },
  { n: "view-timeline-inset", k: "property", d: "", c: "view-timeline-inset: 20%;" },
  { n: "view-timeline-name", k: "property", d: "", c: "view-timeline-name: --v;" },
  { n: "@view-transition", k: "at-rule", d: "ページ遷移定義", c: "@view-transition { navigation: auto; }" },
  { n: "::view-transition", k: "pseudo", d: "遷移全体ルート", c: "::view-transition { background:#000; }" },
  { n: "::view-transition-group()", k: "pseudo", d: "遷移グループ", c: "::view-transition-group(root) { }" },
  { n: "::view-transition-image-pair()", k: "pseudo", d: "旧/新画像ペア", c: "::view-transition-image-pair(root) { }" },
  { n: "::view-transition-old()", k: "pseudo", d: "遷移前画像", c: "::view-transition-old(root) { }" },
  { n: "view-transition-name", k: "property", d: "遷移対象の名前", c: "view-transition-name: hero;" },
  { n: "::view-transition-new()", k: "pseudo", d: "遷移後画像", c: "::view-transition-new(root) { }" },
  { n: "visibility", k: "property", d: "表示/不可視", c: "visibility: hidden;" },
  { n: ":visited", k: "pseudo", d: "訪問済みリンク", c: "a:visited { color: purple; }" },
  { n: "voice-family", k: "property", d: "読み上げの声", c: "voice-family: female;" },
  { n: "volume", k: "property", d: "読み上げ音量", c: "volume: medium;" },
];

/* ----- W ----- */
REF.W = [
  { n: ":where()", k: "pseudo", d: "優先度0の:is()", c: ":where(h1,h2) { color: #333; }" },
  { n: "white-space", k: "property", d: "空白・改行処理", c: "white-space: nowrap;",
    p: `<div style="white-space:nowrap;overflow:hidden;width:120px;border:1px dashed #ccc">折り返しを行わない長い文字列</div>` },
  { n: "white-space-collapse", k: "property", d: "空白の畳み込み", c: "white-space-collapse: preserve;" },
  { n: "white-space-trim", k: "property", d: "行末空白の削除", c: "white-space-trim: discard-before;" },
  { n: "widows", k: "property", d: "改ページ末尾の最小行", c: "widows: 3;" },
  { n: "width", k: "property", d: "幅", c: "width: 100%;" },
  { n: "will-change", k: "property", d: "最適化ヒント", c: "will-change: transform;" },
  { n: "word-break", k: "property", d: "語の分断", c: "word-break: break-all;" },
  { n: "word-spacing", k: "property", d: "語間", c: "word-spacing: 0.2em;" },
  { n: "word-wrap", k: "property", d: "旧称(overflow-wrap)", c: "word-wrap: break-word;" },
  { n: "writing-mode", k: "property", d: "縦書き/横書き", c: "writing-mode: vertical-rl;",
    p: `<div style="writing-mode:vertical-rl;height:50px">縦書き</div>` },
];

/* ----- Z ----- */
REF.Z = [
  { n: "z-index", k: "property", d: "重なり順", c: "z-index: 10;" },
  { n: "zoom", k: "property", d: "拡大率", c: "zoom: 1.2;" },
];

/* ==========================================
   レンダラ
   ========================================== */

function kindLabel(k) {
  const map = {
    selector: "セレクタ", property: "プロパティ", function: "関数",
    "at-rule": "@規則", pseudo: "擬似", type: "データ型", global: "値"
  };
  return map[k] || k;
}

function renderCards(sectionId, items) {
  const sec = document.getElementById(sectionId);
  if (!sec) return;
  const grid = sec.querySelector(".ref-grid");
  if (!grid) return;
  const frag = document.createDocumentFragment();
  for (const it of items) {
    const card = document.createElement("div");
    card.className = "ref-card" + (it.p ? "" : " no-preview");
    const kind = document.createElement("span");
    kind.className = "ref-kind " + it.k;
    kind.textContent = kindLabel(it.k);
    card.appendChild(kind);

    const name = document.createElement("div");
    name.className = "ref-name";
    name.textContent = it.n;
    card.appendChild(name);

    if (it.d) {
      const desc = document.createElement("p");
      desc.className = "ref-desc";
      desc.textContent = it.d;
      card.appendChild(desc);
    }

    if (it.p) {
      const prev = document.createElement("div");
      prev.className = "ref-preview";
      prev.innerHTML = it.p;
      card.appendChild(prev);
    }

    const code = document.createElement("pre");
    code.className = "ref-code";
    code.textContent = it.c;
    card.appendChild(code);

    frag.appendChild(card);
  }
  grid.appendChild(frag);
}

document.addEventListener("DOMContentLoaded", () => {
  renderCards("sec-sym", REF.sym);
  const letters = "ABCDEFGHIJKLMNOPQRSTUVWZ";
  for (const L of letters) {
    renderCards("sec-" + L, REF[L] || []);
  }
  // Lucideアイコンの再描画
  if (window.lucide && typeof window.lucide.createIcons === "function") {
    window.lucide.createIcons();
  }
});
